version: '3'

services:
  rdesktop_base_builtin:
    image: stainless403/rdesktop-base_mdcx-builtin:${MDCX_BUILTIN_IMAGE_TAG}
    container_name: ${MDCX_BUILTIN_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      # 系统数据目录
      - ./data:/config

      # 应用配置目录
      - ./mdcx-config:/mdcx-config
      # 记录当前`配置文件目录`的状态文件
      - ./mdcx-config/MDCx.config:/app/MDCx.config

      # 应用日志目录
      - ./logs:/app/Log

      # 影片目录
      - /path/to/movies:/movies
    # environment:
    ports:
      - ${WEB_PORT}:3000
      - ${RDP_PORT}:3389
    # devices:
    #   - /dev/dri:/dev/dri
    restart: unless-stopped
    network_mode: bridge
    stdin_open: true
