name: Sync docs to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Sync gui-base/mdcx-builtin.md
        uses: northsea4/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/mdcx-builtin-gui-base
          readme: gui-base/mdcx-builtin.md
      - 
        name: Sync gui-base/mdcx-src.md
        uses: northsea4/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/mdcx-src-gui-base
          readme: gui-base/mdcx-src.md
      - 
        name: Sync webtop-base/mdcx-builtin.md
        uses: northsea4/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/mdcx-builtin-webtop-base
          readme: webtop-base/mdcx-builtin.md
      - 
        name: Sync webtop-base/mdcx-src.md
        uses: northsea4/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/mdcx-src-webtop-base
          readme: webtop-base/mdcx-src.md
